version: '3.8'

services:
  tracker:
    container_name: OPtracker_tracker
    build:
      context: ./OPTracker_tracker
    volumes:
      - ./OPTracker_tracker:/app
      - type: bind
        source: ./config.ts
        target: /app/config.ts
    ports:
      - "3000:3000"
    environment:
      - BUN_ENV=development
      - POSTGRES_URL=postgres://ImAnAlbatraoz:strongpassword@postgres:5432/OPtracker
    depends_on:
      - optracker_db
      - redis
    networks:
      - OPNetwork

  api:
    container_name: OPtracker_API
    build:
      context: ./OPTracker_API
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./OPTracker_API/.env
    volumes:
      - ./OPTracker_API/config:/opt/app/config
      - ./OPTracker_API/src:/opt/app/src
      - ./OPTracker_API/package.json:/opt/package.json
      - ./OPTracker_API/yarn.lock:/opt/yarn.lock
      - ./OPTracker_API/.env:/opt/app/.env
      - ./OPTracker_API/public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    environment:
      - BUN_ENV=development
      - HOST=0.0.0.0
      - PORT=1337
      - APP_KEYS=uYFeBM3KC3NNFR8jB6G17g==,qWrP+nmUfwks2mS4bCAe7w==,KNScYpF3eHGffATPaIUc4g==,qG4R5HrfQ6+GddSyeYXzbg==
      - API_TOKEN_SALT=xPP38uEGYlb9Wpq9qGhMGQ==
      - ADMIN_JWT_SECRET=WrFr4TrZhq4yL8S8L+KYJw==
      - TRANSFER_TOKEN_SALT=rR0hjHxqrNlLMtf/h7sGFg==
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=127.0.0.1
      - DATABASE_PORT=5433
      - DATABASE_NAME=optracker_db
      - DATABASE_USERNAME=optracker
      - DATABASE_PASSWORD=changeMeOpTracker
      - DATABASE_SSL=false
      - JWT_SECRET=iEDM7A1fte3G3cNZPgl3QQ==
    depends_on:
      - optracker_db
    networks:
      - OPNetwork

  nginx:
    image: nginx:alpine
    container_name: OPtracker_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - OPNetwork
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - tracker

  optracker_db:
    image: postgres:15
    container_name: optracker_db
    restart: always
    environment:
      POSTGRES_USER: optracker
      POSTGRES_PASSWORD: changeMeOpTracker
      POSTGRES_DB: optracker_db
      PGTZ: Europe/Paris
    volumes:
      - optracker_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - OPNetwork
  redis:
    image: redis:alpine
    container_name: OPtracker_redis
    volumes:
      - redis_data:/data
    networks:
      - OPNetwork
    ports:
      - "6379:6379"
    restart: always

volumes:
  optracker_db_data:
  redis_data:

networks:
  OPNetwork:
    driver: bridge
