version: '3.8'

services:
  tracker:
    container_name: OPtracker_tracker
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - BUN_ENV=development
      - POSTGRES_URL=postgres://ImAnAlbatraoz:strongpassword@postgres:5432/OPtracker
    depends_on:
      - postgres
      - redis
    networks:
      - tracker_network
    restart: always

  postgres:
    image: postgres:15-alpine
    container_name: OPtracker_database
    environment:
      POSTGRES_USER: ImAnAlbatraoz
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: OPtracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tracker_network
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    container_name: OPtracker_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - tracker_network
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - tracker

  redis:
    image: redis:alpine
    container_name: OPtracker_redis
    volumes:
      - redis_data:/data
    networks:
      - tracker_network
    ports:
      - "6379:6379"
    restart: always

networks:
  tracker_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
